### ISSUE TITLE
Repo intro

### ISSUE THREAD

**Issue by raquellrios** [CCPBioSim/BioSim-analysis-workshop#4]
- Adding  the **target student** audience  (master, undergrad...) to the course description will increase it usability. I believe it will make it easier for students to determine if they have the right knowledge for the course, as well as for teachers to quickly assess if they can use the material. 
- **Typo** in name of L5 and P5 title: Analyses --> Analysis

**Comment by raquellrios** [comment]
I see now that the target audience is included in the paper.md Could this be added of the description in the README file of the repo? I think it would be very useful!

**Comment by degiacom** [comment]
Thank you for your feedback! Adding target audience information in README.md file is definitely useful, this has now been done. Concerning the typo, we were going for the plural of "analysis".
